name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GH_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 300

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
