name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 100
          SETTING_JSON: './profile-settings.json'

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git.config user.email github-actions@github.com
          git add -A .
          if git diff --quiet; then
            echo "Nada para commitar."
          else
            git commit -m "generated"
            git push
          fi
